# Cloudflare Pages Configuration
# This configuration tells Cloudflare Pages how to build the site.
#
# The build process:
# 1. Runs gather_links.py to generate gathered_links.json and tools.json
# 2. Runs build_colophon.py to generate colophon.html
# 3. Note: write_docs.py is NOT run (it generates LLM descriptions using API calls)
# 4. Builds the Jekyll site to _site directory
#
# To use this configuration:
# - Connect your GitHub repository to Cloudflare Pages
# - Cloudflare will automatically detect and use this wrangler.toml
# - Or manually configure in the Cloudflare Pages dashboard:
#   - Build command: ./build.sh
#   - Build output directory: _site

name = "tools-simonwillison-net"
compatibility_date = "2025-01-01"

pages_build_output_dir = "_site"

[build]
command = "./build.sh"
